Repository codesquad-member-2020/baseball-01, pull requests merged in 2020-05, with the labels that each got.

#5 프로젝트 세팅
  client-mobile/.gitignore
  client-mobile/BaseballGameApp/BaseballGameApp.xcodeproj/project.pbxproj
  client-mobile/BaseballGameApp/BaseballGameApp.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  client-mobile/BaseballGameApp/BaseballGameApp.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  client-mobile/BaseballGameApp/BaseballGameApp/AppDelegate.swift
  client-mobile/BaseballGameApp/BaseballGameApp/Assets.xcassets/AppIcon.appiconset/Contents.json
  client-mobile/BaseballGameApp/BaseballGameApp/Assets.xcassets/Contents.json
  client-mobile/BaseballGameApp/BaseballGameApp/Base.lproj/LaunchScreen.storyboard
  client-mobile/BaseballGameApp/BaseballGameApp/Base.lproj/Main.storyboard
  client-mobile/BaseballGameApp/BaseballGameApp/Info.plist
  client-mobile/BaseballGameApp/BaseballGameApp/SceneDelegate.swift
  client-mobile/BaseballGameApp/BaseballGameApp/ViewController.swift
Labels: enhancement, iOS

#10 프로젝트 세팅
  be/.gitignore
  be/build.gradle
  be/gradle/wrapper/gradle-wrapper.jar
  be/gradle/wrapper/gradle-wrapper.properties
  be/gradlew
  be/gradlew.bat
  be/settings.gradle
  be/src/main/java/com/codesquad/baseball1/Baseball1Application.java
  be/src/main/resources/application.properties
  be/src/main/resources/logback.xml
  be/src/test/java/com/codesquad/baseball1/Baseball1ApplicationTests.java
Labels: BE, enhancement

#18 기본 라우트 정의
  client-web/baseball/package-lock.json
  client-web/baseball/package.json
  client-web/baseball/src/App.js
  client-web/baseball/src/Components/Intro.js
  client-web/baseball/src/Components/MatchUp.js
  client-web/baseball/src/Components/NoMatch.js
  client-web/baseball/src/Components/Play.js
  client-web/baseball/src/Components/Routes.js
  client-web/baseball/src/Data/team.json
Labels: FE

#19 게임 매치리스트 뷰컨트롤러 구현
  client-mobile/BaseballGameApp/BaseballGameApp.xcodeproj/project.pbxproj
  client-mobile/BaseballGameApp/BaseballGameApp/Assets.xcassets/baseball.imageset/Contents.json
  client-mobile/BaseballGameApp/BaseballGameApp/Assets.xcassets/baseball.imageset/baseball.png
  client-mobile/BaseballGameApp/BaseballGameApp/Assets.xcassets/codesquad.imageset/Contents.json
  client-mobile/BaseballGameApp/BaseballGameApp/Assets.xcassets/codesquad.imageset/codesquad.png
  client-mobile/BaseballGameApp/BaseballGameApp/Assets.xcassets/logo.doosan.imageset/Contents.json
  client-mobile/BaseballGameApp/BaseballGameApp/Assets.xcassets/logo.doosan.imageset/logo.doosan.png
  client-mobile/BaseballGameApp/BaseballGameApp/Base.lproj/Main.storyboard
  client-mobile/BaseballGameApp/BaseballGameApp/Extensions/AutoLayout.swift
  client-mobile/BaseballGameApp/BaseballGameApp/MatchListViewController.swift
  client-mobile/BaseballGameApp/BaseballGameApp/SceneDelegate.swift
  client-mobile/BaseballGameApp/BaseballGameApp/ViewController.swift
  client-mobile/BaseballGameApp/BaseballGameApp/Views/LogoImageView.swift
  client-mobile/BaseballGameApp/BaseballGameApp/Views/MatchCell.swift
  client-mobile/BaseballGameApp/BaseballGameApp/Views/MatchListCollectionView.swift
  client-mobile/BaseballGameApp/BaseballGameApp/Views/MatchPopupView.swift
  client-mobile/BaseballGameApp/BaseballGameApp/Views/PlainLabel.swift
Labels: feature, iOS

#20 초기 화면 VIEW
  client-web/baseball/package-lock.json
  client-web/baseball/package.json
  client-web/baseball/public/index.html
  client-web/baseball/src/App.js
  client-web/baseball/src/Components/Intro.js
  client-web/baseball/src/Components/Intro/Loader.js
  client-web/baseball/src/Components/Intro/StartLink.js
  client-web/baseball/src/Components/Intro/Title.js
  client-web/baseball/src/Components/Intro/index.js
  client-web/baseball/src/Components/MatchUp.js
  client-web/baseball/src/Components/Routes.js
  client-web/baseball/src/Components/Styles/Backgorund.js
  client-web/baseball/src/Components/Styles/GlobalStyle.js
  client-web/baseball/src/Components/Styles/Keyframes.js
  client-web/baseball/src/Components/Styles/baseball.png
  client-web/baseball/src/Components/Styles/intro_bg.png
Labels: FE

#21 메인 뷰컨트롤러 구현
  client-mobile/BaseballGameApp/BaseballGameApp.xcodeproj/project.pbxproj
  client-mobile/BaseballGameApp/BaseballGameApp/Assets.xcassets/baseball.imageset/baseball.png
  client-mobile/BaseballGameApp/BaseballGameApp/Assets.xcassets/signin.main.imageset/Contents.json
  client-mobile/BaseballGameApp/BaseballGameApp/Assets.xcassets/signin.main.imageset/main3.jpg
  client-mobile/BaseballGameApp/BaseballGameApp/Info.plist
  client-mobile/BaseballGameApp/BaseballGameApp/ViewControllers/MainViewController.swift
  client-mobile/BaseballGameApp/BaseballGameApp/ViewControllers/MatchListViewController.swift
  images/logo/Doosan.png
  images/logo/Hanwha.png
  images/logo/Kia.png
  images/logo/Kiwoom.png
  images/logo/Kt.png
  images/logo/Lg.png
  images/logo/Lotte.png
  images/logo/Nc.png
  images/logo/Samsung.png
  images/logo/Sk.png
Labels: feature, iOS

#30 매치리스트 api 구현
  be/src/main/java/com/codesquad/baseball1/controller/MatchController.java
  be/src/main/java/com/codesquad/baseball1/dao/MatchDao.java
  be/src/main/java/com/codesquad/baseball1/dto/MatchDto.java
  be/src/main/java/com/codesquad/baseball1/dto/ResponseDto.java
  be/src/main/java/com/codesquad/baseball1/dto/TeamDto.java
  be/src/main/java/com/codesquad/baseball1/service/MatchService.java
  be/src/main/resources/application.properties
  be/src/main/resources/data.sql
  be/src/main/resources/schema.sql
Labels: BE, enhancement

#35 로그 생성 api 구현
  be/src/main/java/com/codesquad/baseball1/controller/LogController.java
  be/src/main/java/com/codesquad/baseball1/dao/InningDao.java
  be/src/main/java/com/codesquad/baseball1/dao/LogDao.java
  be/src/main/java/com/codesquad/baseball1/dao/RecordDao.java
  be/src/main/java/com/codesquad/baseball1/domain/HalfInning.java
  be/src/main/java/com/codesquad/baseball1/domain/Hitter.java
  be/src/main/java/com/codesquad/baseball1/domain/Log.java
  be/src/main/java/com/codesquad/baseball1/domain/Record.java
  be/src/main/java/com/codesquad/baseball1/domain/Team.java
  be/src/main/java/com/codesquad/baseball1/dto/ResponseDto.java
  be/src/main/resources/data.sql
  be/src/main/resources/schema.sql
Labels: BE, feature

#38 멀티 유저 팀 선택 기능 구현
  be/src/main/java/com/codesquad/baseball1/controller/MatchController.java
  be/src/main/java/com/codesquad/baseball1/dao/MatchDao.java
  be/src/main/java/com/codesquad/baseball1/dto/ResponseDto.java
  be/src/main/java/com/codesquad/baseball1/dto/TeamDto.java
  be/src/main/java/com/codesquad/baseball1/dto/TeamStatusDto.java
  be/src/main/java/com/codesquad/baseball1/service/MatchService.java
  be/src/main/resources/data.sql
  be/src/main/resources/schema.sql
Labels: BE, enhancement

#39 상세 점수 팝업, 선수 정보 팝업 화면 api 구현
  be/src/main/java/com/codesquad/baseball1/SimpleCorsFilter.java
  be/src/main/java/com/codesquad/baseball1/WebConfig.java
  be/src/main/java/com/codesquad/baseball1/controller/LogController.java
  be/src/main/java/com/codesquad/baseball1/controller/PitchController.java
  be/src/main/java/com/codesquad/baseball1/controller/PlayersController.java
  be/src/main/java/com/codesquad/baseball1/controller/ScoreController.java
  be/src/main/java/com/codesquad/baseball1/controller/SetupController.java
  be/src/main/java/com/codesquad/baseball1/dao/InningDao.java
  be/src/main/java/com/codesquad/baseball1/dao/MatchDao.java
  be/src/main/java/com/codesquad/baseball1/dao/PlayerInfoDao.java
  be/src/main/java/com/codesquad/baseball1/dao/RecordDao.java
  be/src/main/java/com/codesquad/baseball1/dao/SetupDao.java
  be/src/main/java/com/codesquad/baseball1/domain/HalfInning.java
  be/src/main/java/com/codesquad/baseball1/domain/Hitter.java
  be/src/main/java/com/codesquad/baseball1/dto/BoardDto.java
  be/src/main/java/com/codesquad/baseball1/dto/PlayerInfoDto.java
  be/src/main/java/com/codesquad/baseball1/dto/ResponseDto.java
  be/src/main/java/com/codesquad/baseball1/dto/ScoreDto.java
  be/src/main/java/com/codesquad/baseball1/dto/SetupDto.java
  be/src/main/java/com/codesquad/baseball1/service/LogService.java
  be/src/main/resources/data.sql
  be/src/main/resources/schema.sql
Labels: BE, enhancement

#40 플레이 뷰컨트롤러 UI 구현
  client-mobile/BaseballGameApp/BaseballGameApp.xcodeproj/project.pbxproj
  client-mobile/BaseballGameApp/BaseballGameApp/Assets.xcassets/arrowtriangle.left.fill.symbolset/Contents.json
  client-mobile/BaseballGameApp/BaseballGameApp/Assets.xcassets/arrowtriangle.left.fill.symbolset/arrowtriangle.left.fill.svg
  client-mobile/BaseballGameApp/BaseballGameApp/Assets.xcassets/base.occupied.colorset/Contents.json
  client-mobile/BaseballGameApp/BaseballGameApp/Assets.xcassets/board.view.colorset/Contents.json
  client-mobile/BaseballGameApp/BaseballGameApp/Assets.xcassets/count.board.ball.colorset/Contents.json
  client-mobile/BaseballGameApp/BaseballGameApp/Assets.xcassets/count.board.empty.colorset/Contents.json
  client-mobile/BaseballGameApp/BaseballGameApp/Assets.xcassets/count.board.inner.bg.colorset/Contents.json
  client-mobile/BaseballGameApp/BaseballGameApp/Assets.xcassets/count.board.out.colorset/Contents.json
  client-mobile/BaseballGameApp/BaseballGameApp/Assets.xcassets/count.board.strike.colorset/Contents.json
  client-mobile/BaseballGameApp/BaseballGameApp/Assets.xcassets/logo.default.imageset/Contents.json
  client-mobile/BaseballGameApp/BaseballGameApp/Assets.xcassets/logo.default.imageset/default_team_logo.png
  client-mobile/BaseballGameApp/BaseballGameApp/Assets.xcassets/logo.doosan.imageset/logo.doosan.png
  client-mobile/BaseballGameApp/BaseballGameApp/Assets.xcassets/match.board.current.player.bar.colorset/Contents.json
  client-mobile/BaseballGameApp/BaseballGameApp/Assets.xcassets/play.backgroound.imageset/Contents.json
  client-mobile/BaseballGameApp/BaseballGameApp/Assets.xcassets/play.backgroound.imageset/play.background.jpg
  client-mobile/BaseballGameApp/BaseballGameApp/Assets.xcassets/tabbar.icon.play.imageset/Contents.json
  client-mobile/BaseballGameApp/BaseballGameApp/Assets.xcassets/tabbar.icon.play.imageset/icons8-softball-mitt-50.png
  client-mobile/BaseballGameApp/BaseballGameApp/Base.lproj/Main.storyboard
  client-mobile/BaseballGameApp/BaseballGameApp/Extensions/AutoLayout.swift
  client-mobile/BaseballGameApp/BaseballGameApp/Info.plist
  client-mobile/BaseballGameApp/BaseballGameApp/ViewControllers/MatchListViewController.swift
  client-mobile/BaseballGameApp/BaseballGameApp/ViewControllers/PlayTabBar/MatchViewController.swift
  client-mobile/BaseballGameApp/BaseballGameApp/ViewControllers/PlayTabBar/PlayViewController.swift
  client-mobile/BaseballGameApp/BaseballGameApp/Views/MatchPopupView.swift
  client-mobile/BaseballGameApp/BaseballGameApp/Views/Play/BaseBoardBackgroundView.swift
  client-mobile/BaseballGameApp/BaseballGameApp/Views/Play/BaseBoardView.swift
  client-mobile/BaseballGameApp/BaseballGameApp/Views/Play/CountBoardView.swift
  client-mobile/BaseballGameApp/BaseballGameApp/Views/Play/CountBoardView.xib
  client-mobile/BaseballGameApp/BaseballGameApp/Views/Play/CurrentPitcherHitterView.swift
  client-mobile/BaseballGameApp/BaseballGameApp/Views/Play/CurrentPitcherHitterView.xib
  client-mobile/BaseballGameApp/BaseballGameApp/Views/Play/MatchBoardView.swift
  client-mobile/BaseballGameApp/BaseballGameApp/Views/Play/PlayerLogCell.swift
  client-mobile/BaseballGameApp/BaseballGameApp/Views/Play/PlayerLogCell.xib
  client-mobile/BaseballGameApp/BaseballGameApp/Views/Play/PlayerLogsHeaderView.swift
  client-mobile/BaseballGameApp/BaseballGameApp/Views/Play/PlayerLogsTableView.swift
  client-mobile/BaseballGameApp/BaseballGameApp/Views/Play/PlayingTeamIndexBar.swift
Labels: feature, iOS

#43 MatchCell 업데이트 구현
  client-mobile/BaseballGameApp/BaseballGameApp/ViewModels/MatchListDataSource.swift
  client-mobile/BaseballGameApp/BaseballGameApp/Views/MatchCell.swift
Labels: feature, iOS

#51 게임 리셋 기능 구현
  be/src/main/java/com/codesquad/baseball1/controller/PitchController.java
  be/src/main/java/com/codesquad/baseball1/controller/ResetController.java
  be/src/main/java/com/codesquad/baseball1/dao/InningDao.java
  be/src/main/java/com/codesquad/baseball1/domain/HalfInning.java
  be/src/main/java/com/codesquad/baseball1/service/HalfInningService.java
  be/src/main/java/com/codesquad/baseball1/service/LogService.java
  be/src/main/java/com/codesquad/baseball1/service/ResetService.java
  be/src/main/resources/application.properties
  be/src/main/resources/data.sql
  be/src/main/resources/schema.sql
Labels: BE, enhancement

#53 팝업 화면 매치 상태 업데이트
  client-mobile/BaseballGameApp/BaseballGameApp.xcodeproj/project.pbxproj
  client-mobile/BaseballGameApp/BaseballGameApp/Assets.xcassets/away.home.label.colorset/Contents.json
  client-mobile/BaseballGameApp/BaseballGameApp/Assets.xcassets/matchlist.bg.imageset/Contents.json
  client-mobile/BaseballGameApp/BaseballGameApp/Assets.xcassets/matchlist.bg.imageset/baseball_bg.jpg
  client-mobile/BaseballGameApp/BaseballGameApp/Base.lproj/Main.storyboard
  client-mobile/BaseballGameApp/BaseballGameApp/Models/MatchStatus.swift
  client-mobile/BaseballGameApp/BaseballGameApp/Models/SelectedTeam.swift
  client-mobile/BaseballGameApp/BaseballGameApp/Models/SelectingStatus.swift
  client-mobile/BaseballGameApp/BaseballGameApp/UseCase/MatchListUseCase.swift
  client-mobile/BaseballGameApp/BaseballGameApp/UseCase/MatchStatusUserCase.swift
  client-mobile/BaseballGameApp/BaseballGameApp/UseCase/SelectTeamUseCase.swift
  client-mobile/BaseballGameApp/BaseballGameApp/ViewControllers/MatchListViewController.swift
  client-mobile/BaseballGameApp/BaseballGameApp/ViewControllers/PlayTabBar/PlayViewController.swift
  client-mobile/BaseballGameApp/BaseballGameApp/ViewModels/MatchListDataSource.swift
  client-mobile/BaseballGameApp/BaseballGameApp/Views/MatchCell.swift
  client-mobile/BaseballGameApp/BaseballGameApp/Views/MatchListCollectionView.swift
  client-mobile/BaseballGameApp/BaseballGameApp/Views/MatchPopupView.swift
  client-mobile/BaseballGameApp/BaseballGameApp/Views/PlainLabel.swift
Labels: feature, iOS

#57 초기화면 설정 업데이트
  client-mobile/BaseballGameApp/BaseballGameApp.xcodeproj/project.pbxproj
  client-mobile/BaseballGameApp/BaseballGameApp/Base.lproj/Main.storyboard
  client-mobile/BaseballGameApp/BaseballGameApp/Models/PlayConfiguration.swift
  client-mobile/BaseballGameApp/BaseballGameApp/Models/PlayerLog.swift
  client-mobile/BaseballGameApp/BaseballGameApp/SceneDelegate.swift
  client-mobile/BaseballGameApp/BaseballGameApp/UseCase/MatchListUseCase.swift
  client-mobile/BaseballGameApp/BaseballGameApp/UseCase/MatchStatusUserCase.swift
  client-mobile/BaseballGameApp/BaseballGameApp/UseCase/PlayConfigurationUseCase.swift
  client-mobile/BaseballGameApp/BaseballGameApp/UseCase/SelectTeamUseCase.swift
  client-mobile/BaseballGameApp/BaseballGameApp/ViewControllers/MatchListViewController.swift
  client-mobile/BaseballGameApp/BaseballGameApp/ViewControllers/PlayTabBar/MatchViewController.swift
  client-mobile/BaseballGameApp/BaseballGameApp/ViewControllers/PlayTabBar/PlayViewController.swift
  client-mobile/BaseballGameApp/BaseballGameApp/ViewModels/PlayerLogsTableDataSource.swift
  client-mobile/BaseballGameApp/BaseballGameApp/Views/Play/CountBoardView.xib
  client-mobile/BaseballGameApp/BaseballGameApp/Views/Play/CurrentPitcherHitterView.swift
  client-mobile/BaseballGameApp/BaseballGameApp/Views/Play/CurrentPitcherHitterView.xib
  client-mobile/BaseballGameApp/BaseballGameApp/Views/Play/MatchBoardView.swift
Labels: feature, iOS

#60 CurrentPitcherHitterView PlayerLabel
  client-mobile/BaseballGameApp/BaseballGameApp/Views/Play/CurrentPitcherHitterView.xib
Labels: hotfix, iOS

#61 매치리스트 주기적으로 요청 Invalidate
  client-mobile/BaseballGameApp/BaseballGameApp/ViewControllers/MatchListViewController.swift
Labels: hotfix, iOS
